DROP TABLE IF EXISTS BEER;
DROP TABLE IF EXISTS BAR;

CREATE TABLE BAR (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250) NOT NULL
);

CREATE TABLE BEER (
	  id INT AUTO_INCREMENT  PRIMARY KEY,
	  name VARCHAR(250) NOT NULL,
	  bar_id INT NOT NULL,
	  quantity FLOAT,
	  FOREIGN KEY (bar_id) REFERENCES BAR(ID)
);

INSERT INTO BAR (name) values ('ONE'), ('TWO'), ('THREE');

